py: Add support for Raspberry Pi Pico
spacecubics/scsat1-mcs pull request #30
Opened 2024-10-22 08:52 UTC by Nari-19

PythonによるXML MDB作成用ScriptにPico対応を追加.

2024-10-22 10:13 UTC, sasataku requested changes

2024-10-22 10:13 UTC, sasataku commented on py/tctm/pico_tm.yaml
> +  - name: GET_TMP
コマンド名は `GET_XXX` で良いのですが、応答のテレメトリには、`GET` はないほうがいいかな。
つけるとしても、`GET_TMP_REPLY` とか。
ひとまず MAIN Boardとかと合わせることにするので、`TEMP` にしてもらえますか？

2024-10-22 10:13 UTC, sasataku commented on py/tctm/pico_tc.yaml
> +      - name: "GET_TMP"
MAIN Boardとかと合わせて `GET_TEMP` にしてもらえますか？

2024-10-22 10:13 UTC, sasataku commented on py/tctm/pico_tc.yaml
> +          - name: "temp"
本来は不要な argumentsですが、 `create_xtce.py` の制限で追加した引数と聞いています。
コミットメッセージに、その説明と、「将来的には argument なしのコマンドも定義できるように `create_xtce.py` を修正する」と書いておいてください。

2024-10-22 10:13 UTC, sasataku commented on py/tctm/pico_tc.yaml
> +          - name: "temp"
`val` がないと、毎回コマンドを打つときに引数の入力が必要になります。
そのような場合は、`val: 0` のように定義してあげると、Yamcsの画面での入力が不要になるので、試してみてください。

2024-10-22 10:13 UTC, sasataku commented on py/create_xtce.py
> +    parser.add_argument("--name", choices=["srs3", "eps", "main", "adcs","pico"])
"," の前に、空白を入れてください。
Python PEP8などで検索するとコードフォーマットしてくれる方法が出てくると思うので調べてみましょう。

2024-10-22 10:21 UTC, sasataku commented on py/tctm/pico_tc.yaml
> +          - name: "temp"
自分が試したら、argumentなしでもXTCEへのパースもYamcsでのロードもできました。

```
diff --git a/py/tctm/pico_tc.yaml b/py/tctm/pico_tc.yaml
index 44b11a2..8dae9c9 100644
--- a/py/tctm/pico_tc.yaml
+++ b/py/tctm/pico_tc.yaml
@@ -19,5 +19,3 @@ default_commands:
     commands:
       - name: "GET_TMP"
         port: 11
-        arguments:
-          - name: "temp"
```

もう１回試してみてもらえますか？

2024-10-22 10:23 UTC, takumiando commented on py/tctm/pico_tc.yaml
> +          - name: "temp"
@sasataku 
パースもロードもできたが、UDPでテレコマンドが送出されない現象でした。
tcpdumpで見れますか？

2024-10-22 10:30 UTC, sasataku commented on py/tctm/pico_tc.yaml
> +          - name: "temp"
確認しました。確かにYamcs上ではコマンド送信されているように見えますが、UDPに出て行ってないですね。
別問題として調査するので、issueをあげて、コミットメッセージにはその暫定対策だという説明をいれましょう。

2024-10-23 00:29 UTC, takumiando commented
VScodeを使っているなら、EOFの設定を再確認。
>Linelint / Check EOF newline

2024-10-25 05:31 UTC, sasataku commented
まだ EOF newlineのテストがfailしているので、確認してみてください。

2024-10-25 05:36 UTC, sasataku commented
Commitメッセージを改善してくれていますが、`etc`, `tctm`, `scripts`, `py`の修正をそれぞれ別のCommitに分けるほうが、説明がしやすくなると思いますし、レビュー指摘を受けてから、修正すべきcommitも限定できます。
4つのコミットに分けるようにしてみてくれますか？

2024-10-25 05:51 UTC, sasataku commented on py/create_xtce.py
> +    PICO = 14
PEP8のエラーが出ると思います。確認してみてください

> create_xtce.py:50:1: E302 expected 2 blank lines, found 1

2024-10-25 08:43 UTC, sasataku commented
修正ありがとう。ソースコードの方は問題ありません。
最後に１個だけ以下のCommit messageを修正してください。

```
commit dd71f2f4bed82f131fe2d539cb6af8aa1066d535
Author: Riho Natsushima <nasshi7224@gmail.com>
Date:   Fri Oct 25 15:48:19 2024 +0900

    tctm: Add support for Raspberry Pi Pico
    
     - Added GET_TEMP command to pico_tc.yaml
     - Added GET_TEMP command to pico_tm.yaml
```

指摘事項:
- `pico_tm.yaml` に追加しているのは、`command`ではなく`telemetry` です。
　なので、 `TEMP telemetryを追加` が正しいと思います。
- それ以外にも、CSP標準の commandと、telemetryも追加しているはずです。
　そのことも commit messageに追加してください。
　(CSP標準の telemetry / telecommand は、MAINを参考にしていることも書いておくとなお良いです)

2024-10-28 02:42 UTC, sasataku approved these changes
Thanks, LGTM.

2024-10-28 02:42 UTC, merged